all:
  vars:
    ansible_user: ansible
    build_number: "{{ ansible_date_time.iso8601_micro | to_uuid }}"
    required_docker_label: "org.codekaizen.application=codekaizen-wp-plugin-registry"
    nginx_reverse_proxy_network_name: "nginx_proxy_network"
    CODEKAIZEN_WP_PLUGIN_REGISTRY_DOMAIN: "{{ lookup('env', 'CODEKAIZEN_WP_PLUGIN_REGISTRY_DOMAIN') }}"
    ORASHUB_PORT: "{{ lookup('env', 'ORASHUB_PORT') }}"
    ORASHUB_REGISTRY: "{{ lookup('env', 'ORASHUB_REGISTRY') }}"
    ORASHUB_REGISTRY_USERNAME: "{{ lookup('env', 'ORASHUB_REGISTRY_USERNAME') }}"
    ORASHUB_REGISTRY_PASSWORD: "{{ lookup('env', 'ORASHUB_REGISTRY_PASSWORD') }}"
    ORASHUB_REGISTRY_NAMESPACE: "{{ lookup('env', 'ORASHUB_REGISTRY_NAMESPACE') }}"
  hosts:
    9c9b38653dae4f4ebbd120adba40ac33:
      ansible_host: 192.168.0.28
      docker_networks: []
      docker_volumes: []
      docker_containers:
        - name: "codekaizen-wp-plugin-registry-server"
          image: "ghcr.io/codekaizen-github/codekaizen-wp-plugin-registry:latest"
          pull: true
          state: "started"
          networks:
            - name: "{{ nginx_reverse_proxy_network_name }}"
              aliases:
                - "{{ CODEKAIZEN_WP_PLUGIN_REGISTRY_DOMAIN }}"
          env:
            ORASHUB_PORT: "{{ ORASHUB_PORT }}"
            ORASHUB_REGISTRY: "{{ ORASHUB_REGISTRY }}"
            ORASHUB_REGISTRY_USERNAME: "{{ ORASHUB_REGISTRY_USERNAME }}"
            ORASHUB_REGISTRY_PASSWORD: "{{ ORASHUB_REGISTRY_PASSWORD }}"
            ORASHUB_REGISTRY_NAMESPACE: "{{ ORASHUB_REGISTRY_NAMESPACE }}"
          labels:
            org.codekaizen.application: "codekaizen-wp-plugin-registry"
            org.codekaizen.service: "server"
          restart_policy: always
          replica_count: 1
          deploy_strategy: "recreate"
          filters_string: '--filter "label=org.codekaizen.service=server"'
